services:
  - type: web
    name: cloud-telegram-py-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python -m src.main
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
